# Site settings
title: Jamie Fang
email: hi&#xFF20;jamiefang&#x2024;com
description: "Pushing pixels behind a screen."
baseurl: ""
url: "http://www.jamiefang.com"
twitter_username: jamiefang
github_username:  jamiefang

# Build settings
markdown: kramdown
# permalink: /articles/:title